services:
  always-voice:
    build: .
    container_name: always-voice-bot
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - TOKEN=${TOKEN:-}
      - GUILD_ID=${GUILD_ID:-}
      - CHANNEL_ID=${CHANNEL_ID:-}
      - VOICE_LIMIT=${VOICE_LIMIT:-0}
      - VOICE_LIMIT_DELAY=${VOICE_LIMIT_DELAY:-300}
      - STATUS=${STATUS:-dnd}
      - SELF_MUTE=${SELF_MUTE:-True}
      - SELF_DEAF=${SELF_DEAF:-False}
      - AUTO_REPLY=${AUTO_REPLY:-True}
      - REPLY_DELAY=${REPLY_DELAY:-5}
      - REPLY_TRIGGER=${REPLY_TRIGGER:-hey wake up!}
      - REPLY_MESSAGE=${REPLY_MESSAGE:-yes}
