services:
  always-voice:
    build: .
    container_name: always-voice-bot
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - TOKEN=${TOKEN}
      - GUILD_ID=${GUILD_ID}
      - CHANNEL_ID=${CHANNEL_ID}
      - STATUS=dnd
      - AUTO_REPLY=True
      - REPLY_TRIGGER=hey wake up!
      - REPLY_MESSAGE=yes